Repository SDUOJ/sduoj-web, pull requests merged in 2020-11, with the labels that each got.

#37 Refactor and polish
  package-lock.json
  package.json
  src/components/CodeEditor.vue
  src/components/NavBar.vue
  src/components/upload/upload-list.vue
  src/components/upload/upload.vue
  src/store/modules/user.js
  src/utils/api.js
  src/utils/constants.js
  src/views/HomeView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/user/ResetPass.vue
  src/views/user/children/UserProfile.vue
Labels: enhancement, styles

#38 Optimize
  src/components/CodeEditor.vue
  src/components/JudgeResult.vue
  src/components/NavBar.vue
  src/components/SubmissionList.vue
  src/utils/constants.js
  src/utils/socket.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestRank.vue
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Login.vue
Labels: enhancement, styles

#39 CICD: GitHub actions
  .github/workflows/build.yml
Labels: enhancement

#40 UED polish
  src/components/ContestProcess.vue
  src/components/SubmissionList.vue
  src/store/modules/contest.js
  src/styles/global.less
  src/utils/constants.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestOverviewView.vue
  src/views/contest/ContestRank.vue
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
Labels: enhancement

#41 bugfix and polish
  package-lock.json
  package.json
  src/components/ContestProcess.vue
  src/components/NavBar.vue
  src/components/SubmissionList.vue
  src/components/mixins/index.js
  src/components/mixins/page.js
  src/main.js
  src/plugins/highlight.js
  src/plugins/iviewui.js
  src/router/index.js
  src/styles/global.less
  src/styles/reset.css
  src/views/HomeView.vue
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestRank.vue
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/UserHome.vue
  src/views/user/children/UserEmail.vue
Labels: bug, enhancement, styles

#42 Submission Rejudge and Bugfix
  package-lock.json
  package.json
  src/components/CodeEditor.vue
  src/components/JudgeResult.vue
  src/components/ProblemCode.vue
  src/components/SubmissionList.vue
  src/components/mixins/page.js
  src/router/index.js
  src/router/routes.js
  src/store/modules/contest.js
  src/store/modules/ranks/acm.js
  src/store/modules/ranks/ioi.js
  src/store/modules/ranks/oi.js
  src/store/modules/user.js
  src/utils/api.js
  src/utils/constants.js
  src/utils/md5.js
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
Labels: bug, enhancement

#43 bugfix
  src/components/SubmissionList.vue
  src/router/index.js
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
Labels: bug

#44 Batch-listening
  src/components/JudgeResult.vue
  src/components/SubmissionList.vue
  src/components/mixins/index.js
  src/components/mixins/page.js
  src/components/mixins/websocket.js
  src/plugins/highlight.js
  src/utils/socket.js
  src/views/submission/SubmissionDetailView.vue
Labels: bug, enhancement

#45 New features on Contest and Problem
  package-lock.json
  package.json
  src/components/CodeEditor.vue
  src/components/ContestProcess.vue
  src/components/JudgeResult.vue
  src/components/Markdown.vue
  src/components/SubmissionList.vue
  src/components/mixins/page.js
  src/store/modules/contest.js
  src/store/modules/ranks/acm.js
  src/store/modules/ranks/ioi.js
  src/store/modules/ranks/oi.js
  src/store/modules/user.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestOverviewView.vue
  src/views/contest/ContestRank.vue
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/UserHome.vue
Labels: bug, enhancement

#47 Add new feature
  src/components/JudgeResult.vue
  src/styles/domjudge.css
  src/utils/api.js
  src/utils/constants.js
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
Labels: enhancement

#48 ballon color
  src/main.js
  src/plugins/highlight.js
  src/router/index.js
  src/styles/rank.css
  src/views/contest/ContestOverviewView.vue
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
Labels: enhancement

#49 Bug fix
  src/plugins/highlight.js
  src/router/index.js
  src/store/modules/ranks/index.js
  src/styles/rank.css
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionView.vue
Labels: bug

#50 add <pre> tag
  src/views/problem/ProblemDetailView.vue
Labels: bug

#51 first blood only belongs to the official participants
  src/plugins/highlight.js
  src/store/modules/contest.js
  src/views/submission/SubmissionDetailView.vue
Labels: enhancement
