Repository SDUOJ/sduoj-web, pull requests merged in 2020-10, with the labels that each got.

#19 题库静态页面完成
  src/App.vue
  src/views/problem/ProblemView.vue
Labels: enhancement

#20 题库数据部署
  package-lock.json
  src/utils/api.js
  src/views/problem/ProblemView.vue
Labels: enhancement

#21 adjust API with backend.
  src/App.vue
  src/components/CodeEditor.vue
  src/components/JudgeResult.vue
  src/components/NavBar.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/user.js
  src/styles/global.less
  src/utils/DateFormat.js
  src/utils/api.js
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Login.vue
  src/views/user/Register.vue
  src/views/user/ResetPass.vue
  src/views/user/UserHome.vue
  src/views/user/children/UserEmail.vue
  src/views/user/children/UserPassword.vue
  src/views/user/children/UserProfile.vue
Labels: enhancement

#22 jeshrz/problem
  src/App.vue
  src/components/Card.vue
  src/components/NavPath.vue
  src/styles/global.less
  src/styles/icons/icon-线-04.svg
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/user/children/UserProfile.vue
Labels: styles

#24 Contest basic layout
  package-lock.json
  package.json
  src/App.vue
  src/components/JudgeResult.vue
  src/router/routes.js
  src/store/index.js
  src/styles/global.less
  src/styles/iview-component.less
  src/utils/api.js
  src/utils/index.js
  src/utils/time.js
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionView.vue
Labels: enhancement, styles

#26 Jeshrz/contest detail
  .gitignore
  package-lock.json
  package.json
  src/App.vue
  src/components/ContestProblem.vue
  src/components/JudgeResult.vue
  src/components/NavBar.vue
  src/router/index.js
  src/router/routes.js
  src/store/index.js
  src/store/modules/contest.js
  src/store/modules/user.js
  src/styles/global.less
  src/styles/iview-component.less
  src/styles/iview-variables.less
  src/utils/api.js
  src/utils/index.js
  src/utils/judge.js
  src/utils/socket.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestView.vue
  src/views/contest/children/ContestOverviewView.vue
  src/views/contest/children/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Login.vue
  src/views/user/Register.vue
  src/views/user/ResetPass.vue
  src/views/user/UserHome.vue
  src/views/user/children/UserEmail.vue
  src/views/user/children/UserPassword.vue
  src/views/user/children/UserProfile.vue
  vue.config.js
Labels: enhancement, styles

#27 Jeshrz/license
  LICENSE
  package-lock.json
  src/App.vue
  src/components/CodeEditor.vue
  src/components/ContestProblem.vue
  src/components/JudgeResult.vue
  src/components/NavBar.vue
  src/components/ProblemCode.vue
  src/main.js
  src/plugins/clipboard2.js
  src/router/index.js
  src/router/routes.js
  src/store/index.js
  src/store/modules/contest.js
  src/store/modules/user.js
  src/utils/api.js
  src/utils/index.js
  src/utils/judge.js
  src/utils/md5.js
  src/utils/socket.js
  src/utils/time.js
  src/views/404View.vue
  src/views/HomeView.vue
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestView.vue
  src/views/contest/children/ContestOverviewView.vue
  src/views/contest/children/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Login.vue
  src/views/user/Register.vue
  src/views/user/ResetPass.vue
  src/views/user/UserHome.vue
  src/views/user/children/UserEmail.vue
  src/views/user/children/UserPassword.vue
  src/views/user/children/UserProfile.vue
Labels: documentation

#28 finish 404 page
  src/assets/404.png
  src/assets/default.png
  src/views/404View.vue
Labels: enhancement

#30 correct show dynamic judging after refresh the page
  src/router/index.js
  src/utils/api.js
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/user/Login.vue
Labels: enhancement
