Repository SDUOJ/sduoj-web, pull requests merged in 2021-05, with the labels that each got.

#72 refactor: adjust submission list, contest list and submission detail.
  src/components/contest/ContestList.vue
  src/components/submission/SubmissionList.vue
  src/views/submission/SubmissionDetailView.vue
Labels: bugfix, refactor

#73 bugfix: resolve null pointer when commit updateNow; refresh page after participated in contest.
  src/store/modules/contest.js
  src/utils/api.js
  src/views/contest/ContestOverviewView.vue
Labels: type: bug

#74 feat: add new judge result 'OLE'
  src/components/submission/SubmissionList.vue
  src/utils/constants.js
Labels: type: enhancement

#79 bugfix: paging error in querying submissions from contest rank cell
  src/views/contest/ContestRankView.vue
Labels: type: bug

#81 feat: third party certification
  src/components/Reconfirm.vue
  src/components/form/login/AccountLoginForm.vue
  src/components/form/register/AccountRegisterForm.vue
  src/components/group/GroupCard.vue
  src/router/routes.js
  src/utils/api.js
  src/views/third-party/Bind.vue
  src/views/third-party/ThirdPartyLogin.vue
  src/views/third-party/css/loader.css
  src/views/third-party/js/ThirdPartyEnum.js
  src/views/user/Login.vue
  src/views/user/Register.vue
  src/views/user/UserHome.vue
Labels: type: enhancement

#80 feat: add contest rank summary part
  src/components/contest/ContestList.vue
  src/main.js
  src/store/modules/contest.js
  src/styles/font/iconfont.ttf
  src/styles/font/iconfont.woff
  src/styles/font/iconfont.woff2
  src/styles/global.less
  src/styles/iconfont.css
  src/views/contest/ContestRankView.vue
Labels: type: enhancement

#84 refactor: email field's biz in user module
  src/components/form/EmailVerify.vue
  src/components/form/register/AccountRegisterForm.vue
  src/store/modules/user.js
  src/utils/api.js
  src/utils/md5.js
  src/views/user/Register.vue
  src/views/user/children/UserEmail.vue
  src/views/user/children/UserPassword.vue
  src/views/user/children/UserProfile.vue
  vue.config.js
Labels: type: task
