Repository SDUOJ/sduoj-web, pull requests merged in 2021-01, with the labels that each got.

#56 happy new year
  src/App.vue
  src/components/CodeEditor.vue
  src/components/ContestProcess.vue
  src/components/JudgeResult.vue
  src/components/NavBar.vue
  src/components/ProblemCode.vue
  src/components/SubmissionList.vue
  src/components/mixins/index.js
  src/components/mixins/page.js
  src/components/mixins/websocket.js
  src/main.js
  src/plugins/clipboard2.js
  src/plugins/highlight.js
  src/router/index.js
  src/router/routes.js
  src/store/index.js
  src/store/modules/contest.js
  src/store/modules/ranks/acm.js
  src/store/modules/ranks/index.js
  src/store/modules/ranks/ioi.js
  src/store/modules/ranks/oi.js
  src/store/modules/user.js
  src/styles/global.less
  src/utils/api.js
  src/utils/constants.js
  src/utils/md5.js
  src/utils/transform.js
  src/views/404View.vue
  src/views/HomeView.vue
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestOverviewView.vue
  src/views/contest/ContestRank.vue
  src/views/contest/ContestView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Login.vue
  src/views/user/Register.vue
  src/views/user/ResetPass.vue
  src/views/user/UserHome.vue
  src/views/user/children/UserEmail.vue
  src/views/user/children/UserPassword.vue
  src/views/user/children/UserProfile.vue
Labels: documentation

#55 Rank Export
  package-lock.json
  package.json
  src/components/Markdown.vue
  src/components/SubmissionList.vue
  src/router/routes.js
  src/store/modules/contest.js
  src/store/modules/ranks/acm.js
  src/store/modules/ranks/ioi.js
  src/store/modules/ranks/oi.js
  src/styles/rank.css
  src/utils/excel.js
  src/utils/transform.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestOverviewView.vue
  src/views/contest/ContestRank.vue
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionView.vue
  src/views/user/Register.vue
Labels: enhancement

#58 Jeshrz/bugfix 21 01 14
  package-lock.json
  package.json
  src/components/CodeEditor.vue
  src/components/Markdown.vue
  src/components/NavBar.vue
  src/components/mixins/websocket.js
  src/utils/env.js
  vue.config.js
Labels: enhancement

#60 fix: show problem title correctly
  src/views/submission/SubmissionDetailView.vue
Labels: bugfix

#61 Jeshrz/groups
  src/components/NavBar.vue
  src/components/UserCard.vue
  src/components/contest/ContestList.vue
  src/components/contest/ContestProcess.vue
  src/components/editor/CodeEditor.vue
  src/components/editor/Markdown.vue
  src/components/group/ContestInGroup.vue
  src/components/group/GroupCard.vue
  src/components/mixins/page.js
  src/components/problem/ProblemCode.vue
  src/components/submission/SubmissionList.vue
  src/router/routes.js
  src/store/modules/contest.js
  src/store/modules/user.js
  src/styles/global.less
  src/styles/iview-component.less
  src/utils/api.js
  src/utils/constants.js
  src/utils/md5.js
  src/views/contest/ContestDetailView.vue
  src/views/contest/ContestListView.vue
  src/views/contest/ContestRankView.vue
  src/views/contest/ContestView.vue
  src/views/group/GroupDetailView.vue
  src/views/group/GroupListView.vue
  src/views/problem/ProblemDetailView.vue
  src/views/problem/ProblemListView.vue
  src/views/submission/SubmissionDetailView.vue
  src/views/submission/SubmissionListView.vue
  src/views/user/UserHome.vue
Labels: bugfix, enhancement

#62 fix: correctly listen to websocket in SubmissionList
  src/components/submission/SubmissionList.vue
  src/views/contest/ContestRankView.vue
  src/views/submission/SubmissionListView.vue
Labels: bugfix
