Repository SDUOJ/sduoj-web, pull requests merged in 2021-03, with the labels that each got.

#63 show ContestList in GroupDetail correctly
  src/components/group/ContestInGroup.vue
  src/views/group/GroupDetailView.vue
Labels: bugfix

#64 copywriting: change exit to quit
  src/components/group/GroupCard.vue
  src/utils/api.js
Labels: refactor

#66 bugfix: the cell of rank table style error
  src/store/modules/ranks/ioi.js
Labels: bug

#68 feat: upload zip file when creating submission; bugfix: scroll bar
  src/components/editor/CodeEditor.vue
  src/styles/global.less
  src/utils/api.js
  src/views/problem/ProblemDetailView.vue
  src/views/submission/SubmissionDetailView.vue
Labels: bugfix, enhancement
